import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { SectionHeading } from "@/components/SectionHeading";
import { adminReports, adminStats, adminUsers, analyticsHighlights } from "@/content/adminData";
import { blogArticles, categorizedFaqs } from "@/content/contentHubData";
export function AdminDashboardPage() {
    return (_jsxs("div", { children: [_jsx("section", { className: "section-shell pb-10 pt-16", children: _jsx(SectionHeading, { eyebrow: "Admin dashboard", title: "Moderation, content, and growth visibility in one place", description: "A moderator-facing view of reports, user health, and product momentum." }) }), _jsx("section", { className: "section-shell pt-0", children: _jsx("div", { className: "grid gap-4 sm:grid-cols-2 xl:grid-cols-4", children: adminStats.map((item) => _jsxs("div", { className: "surface-card p-6", children: [_jsx("p", { className: "text-sm text-brand-forest/65", children: item.label }), _jsx("p", { className: "mt-3 font-display text-4xl font-semibold text-brand-ink", children: item.value })] }, item.label)) }) }), _jsx("section", { className: "section-shell pt-0", children: _jsxs("div", { className: "grid gap-6 lg:grid-cols-2", children: [_jsxs("div", { className: "surface-card p-7", children: [_jsx("h2", { className: "font-display text-3xl font-semibold text-brand-ink", children: "Recent reports" }), _jsx("div", { className: "mt-6 grid gap-4", children: adminReports.slice(0, 3).map((report) => _jsxs("div", { className: "rounded-[1.5rem] bg-brand-forest/5 px-5 py-4", children: [_jsxs("p", { className: "font-semibold text-brand-ink", children: [report.reason, " \uFFFD ", report.reportedUser] }), _jsx("p", { className: "mt-2 text-sm text-brand-forest/70", children: report.description })] }, report.id)) })] }), _jsxs("div", { className: "surface-card p-7", children: [_jsx("h2", { className: "font-display text-3xl font-semibold text-brand-ink", children: "Quick links" }), _jsx("div", { className: "mt-6 grid gap-3 text-sm font-semibold", children: [{ label: "Safety reports", href: "/admin/reports" }, { label: "User management", href: "/admin/users" }, { label: "Content management", href: "/admin/content" }, { label: "Analytics", href: "/admin/analytics" }].map((item) => _jsx(Link, { className: "rounded-[1.5rem] bg-brand-forest/5 px-5 py-4 text-brand-forest", to: item.href, children: item.label }, item.href)) })] })] }) })] }));
}
export function AdminReportsPage() {
    return (_jsxs("div", { children: [_jsx("section", { className: "section-shell pb-10 pt-16", children: _jsx(SectionHeading, { eyebrow: "Safety reports", title: "Review, dismiss, warn, suspend, or ban", description: "Moderation tools should make report handling structured and defensible." }) }), _jsx("section", { className: "section-shell pt-0", children: _jsx("div", { className: "grid gap-4", children: adminReports.map((report) => _jsx("div", { className: "surface-card p-7", children: _jsxs("div", { className: "flex flex-wrap items-start justify-between gap-4", children: [_jsxs("div", { children: [_jsxs("p", { className: "text-sm font-semibold uppercase tracking-[0.2em] text-brand-clay", children: [report.id, " \uFFFD ", report.status] }), _jsx("h2", { className: "mt-3 font-display text-3xl font-semibold text-brand-ink", children: report.reason }), _jsxs("p", { className: "mt-3 text-sm leading-7 text-brand-forest/80", children: ["Reporter: ", report.reporter, " \uFFFD Reported user: ", report.reportedUser] }), _jsx("p", { className: "mt-2 text-sm leading-7 text-brand-forest/80", children: report.description }), _jsxs("p", { className: "mt-2 text-sm text-brand-forest/60", children: ["Evidence: ", report.evidence] })] }), _jsxs("div", { className: "flex flex-wrap gap-2 text-sm font-semibold", children: [_jsx("button", { className: "rounded-full border border-brand-forest/15 px-4 py-2 text-brand-forest", children: "Dismiss" }), _jsx("button", { className: "rounded-full border border-brand-forest/15 px-4 py-2 text-brand-forest", children: "Warn" }), _jsx("button", { className: "rounded-full bg-amber-500 px-4 py-2 text-white", children: "Suspend" }), _jsx("button", { className: "rounded-full bg-rose-600 px-4 py-2 text-white", children: "Ban" })] })] }) }, report.id)) }) })] }));
}
export function AdminUsersPage() {
    return (_jsxs("div", { children: [_jsx("section", { className: "section-shell pb-10 pt-16", children: _jsx(SectionHeading, { eyebrow: "User management", title: "Search users, inspect verification, and take action", description: "Moderators need fast visibility into trust, activity, and account history." }) }), _jsx("section", { className: "section-shell pt-0", children: _jsx("div", { className: "grid gap-4", children: adminUsers.map((user) => _jsx("div", { className: "surface-card p-7", children: _jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h2", { className: "font-display text-3xl font-semibold text-brand-ink", children: user.name }), _jsxs("p", { className: "mt-2 text-sm text-brand-forest/70", children: [user.email, " \uFFFD ", user.phone] }), _jsx("p", { className: "mt-2 text-sm text-brand-clay", children: user.verified }), _jsxs("p", { className: "mt-2 text-sm text-brand-forest/60", children: ["Joined ", user.joined, " \uFFFD Last active ", user.lastActive] })] }), _jsxs("div", { className: "flex flex-wrap gap-2 text-sm font-semibold", children: [_jsx("button", { className: "rounded-full border border-brand-forest/15 px-4 py-2 text-brand-forest", children: "View profile" }), _jsx("button", { className: "rounded-full border border-amber-200 px-4 py-2 text-amber-700", children: "Suspend" }), _jsx("button", { className: "rounded-full border border-rose-200 px-4 py-2 text-rose-700", children: "Ban" })] })] }) }, user.email)) }) })] }));
}
export function AdminContentPage() {
    return (_jsxs("div", { children: [_jsx("section", { className: "section-shell pb-10 pt-16", children: _jsx(SectionHeading, { eyebrow: "Content management", title: "Manage blog and FAQ content", description: "Editorial content, FAQ updates, and publishing tools belong in one operational surface." }) }), _jsx("section", { className: "section-shell pt-0", children: _jsxs("div", { className: "grid gap-6 lg:grid-cols-2", children: [_jsxs("div", { className: "surface-card p-7", children: [_jsx("h2", { className: "font-display text-3xl font-semibold text-brand-ink", children: "Blog articles" }), _jsx("div", { className: "mt-6 grid gap-3", children: blogArticles.map((article) => _jsxs("div", { className: "rounded-[1.4rem] bg-brand-forest/5 px-5 py-4", children: [_jsx("p", { className: "font-semibold text-brand-ink", children: article.title }), _jsxs("p", { className: "mt-2 text-sm text-brand-forest/70", children: [article.category, " \uFFFD ", article.publishedAt] })] }, article.slug)) })] }), _jsxs("div", { className: "surface-card p-7", children: [_jsx("h2", { className: "font-display text-3xl font-semibold text-brand-ink", children: "FAQ categories" }), _jsx("div", { className: "mt-6 grid gap-3", children: categorizedFaqs.map((group) => _jsxs("div", { className: "rounded-[1.4rem] bg-brand-forest/5 px-5 py-4", children: [_jsx("p", { className: "font-semibold text-brand-ink", children: group.category }), _jsxs("p", { className: "mt-2 text-sm text-brand-forest/70", children: [group.items.length, " entries"] })] }, group.category)) })] })] }) })] }));
}
export function AdminAnalyticsPage() {
    return (_jsxs("div", { children: [_jsx("section", { className: "section-shell pb-10 pt-16", children: _jsx(SectionHeading, { eyebrow: "Analytics", title: "Monitor growth, retention, and safety patterns", description: "Use operational analytics to understand where the platform is healthy and where intervention is needed." }) }), _jsx("section", { className: "section-shell pt-0", children: _jsx("div", { className: "grid gap-4 md:grid-cols-2 xl:grid-cols-4", children: adminStats.map((item) => _jsxs("div", { className: "surface-card p-6", children: [_jsx("p", { className: "text-sm text-brand-forest/65", children: item.label }), _jsx("p", { className: "mt-3 font-display text-4xl font-semibold text-brand-ink", children: item.value })] }, item.label)) }) }), _jsx("section", { className: "section-shell pt-0", children: _jsx("div", { className: "grid gap-4", children: analyticsHighlights.map((item) => _jsx("div", { className: "surface-card p-6 text-sm leading-7 text-brand-forest/80", children: item }, item)) }) })] }));
}
