import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { Search } from "lucide-react";
import { RevealOnScroll } from "@/components/RevealOnScroll";
import { SectionHeading } from "@/components/SectionHeading";
import { blogArticles, categorizedFaqs } from "@/content/contentHubData";
export function BlogPage() {
    const [query, setQuery] = useState("");
    const [category, setCategory] = useState("All");
    const filteredArticles = useMemo(() => {
        return blogArticles.filter((article) => {
            const matchesCategory = category === "All" || article.category === category;
            const haystack = `${article.title} ${article.excerpt} ${article.category}`.toLowerCase();
            const matchesQuery = haystack.includes(query.trim().toLowerCase());
            return matchesCategory && matchesQuery;
        });
    }, [category, query]);
    const categories = ["All", ...new Set(blogArticles.map((article) => article.category))];
    return (_jsxs("div", { children: [_jsx("section", { className: "section-shell pb-10 pt-16", children: _jsx(SectionHeading, { eyebrow: "Blog", title: "Guidance for better connections, safer conversations, and clearer decisions", description: "Searchable editorial content on genotype, compatibility, profile quality, and relationship safety." }) }), _jsx("section", { className: "section-shell pt-0", children: _jsx("div", { className: "surface-card p-6 sm:p-8", children: _jsxs("div", { className: "grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center", children: [_jsxs("label", { className: "grid gap-2", children: [_jsx("span", { className: "text-sm font-semibold text-brand-forest", children: "Search articles" }), _jsxs("div", { className: "relative", children: [_jsx(Search, { className: "absolute left-4 top-1/2 -translate-y-1/2 text-brand-forest/45", size: 18 }), _jsx("input", { className: "input-shell pl-11", value: query, onChange: (event) => setQuery(event.target.value), placeholder: "Search genotype, safety, culture..." })] })] }), _jsx("div", { className: "flex flex-wrap gap-2 lg:justify-end", children: categories.map((item) => (_jsx("button", { className: `rounded-full px-4 py-2 text-sm font-semibold transition ${category === item ? "bg-brand-forest text-white" : "bg-brand-forest/5 text-brand-forest hover:bg-brand-forest/10"}`, onClick: () => setCategory(item), type: "button", children: item }, item))) })] }) }) }), _jsx("section", { className: "section-shell pt-0", children: _jsx("div", { className: "section-grid", children: filteredArticles.map((article, index) => (_jsx(RevealOnScroll, { delay: index * 70, children: _jsxs("article", { className: "surface-card overflow-hidden p-0", children: [_jsx("img", { alt: article.title, className: "h-56 w-full object-cover", src: article.image }), _jsxs("div", { className: "p-7", children: [_jsxs("p", { className: "text-xs font-semibold uppercase tracking-[0.2em] text-brand-clay", children: [article.category, " \uFFFD ", article.readTime] }), _jsx("h2", { className: "mt-4 font-display text-3xl font-semibold text-brand-ink", children: article.title }), _jsx("p", { className: "mt-4 text-sm leading-7 text-brand-forest/80", children: article.excerpt }), _jsxs("p", { className: "mt-5 text-sm text-brand-forest/65", children: ["By ", article.author, " \uFFFD ", article.publishedAt] }), _jsx(Link, { className: "mt-6 inline-flex rounded-full bg-brand-forest px-5 py-3 text-sm font-semibold text-white transition hover:bg-brand-emerald", to: `/blog/${article.slug}`, children: "Read article" })] })] }) }, article.slug))) }) })] }));
}
function RelatedArticles({ article }) {
    const related = blogArticles.filter((item) => item.slug !== article.slug).slice(0, 3);
    return (_jsx("div", { className: "grid gap-4 md:grid-cols-3", children: related.map((item) => (_jsxs(Link, { className: "surface-card p-6", to: `/blog/${item.slug}`, children: [_jsx("p", { className: "text-xs font-semibold uppercase tracking-[0.2em] text-brand-clay", children: item.category }), _jsx("h3", { className: "mt-4 font-display text-2xl font-semibold text-brand-ink", children: item.title }), _jsx("p", { className: "mt-3 text-sm leading-7 text-brand-forest/80", children: item.excerpt })] }, item.slug))) }));
}
export function BlogArticlePage() {
    const { slug } = useParams();
    const article = blogArticles.find((item) => item.slug === slug) ?? blogArticles[0];
    return (_jsxs("div", { children: [_jsx("section", { className: "section-shell pb-10 pt-16", children: _jsx(RevealOnScroll, { children: _jsxs("div", { className: "max-w-4xl", children: [_jsx("p", { className: "eyebrow", children: article.category }), _jsx("h1", { className: "mt-6 font-display text-5xl font-semibold text-brand-ink", children: article.title }), _jsx("p", { className: "mt-5 text-lg leading-8 text-brand-forest/80", children: article.excerpt }), _jsxs("p", { className: "mt-5 text-sm text-brand-forest/60", children: ["By ", article.author, " \uFFFD ", article.publishedAt, " \uFFFD ", article.readTime] })] }) }) }), _jsx("section", { className: "section-shell pt-0", children: _jsx("div", { className: "overflow-hidden rounded-[2rem]", children: _jsx("img", { alt: article.title, className: "h-[24rem] w-full object-cover", src: article.image }) }) }), _jsx("section", { className: "section-shell pt-0", children: _jsx("div", { className: "mx-auto max-w-4xl grid gap-8", children: article.sections.map((section, index) => (_jsx(RevealOnScroll, { delay: index * 60, children: _jsxs("article", { className: "surface-card p-8", children: [_jsx("h2", { className: "font-display text-3xl font-semibold text-brand-ink", children: section.heading }), _jsx("div", { className: "mt-5 grid gap-4 text-base leading-8 text-brand-forest/80", children: section.body.map((paragraph) => (_jsx("p", { children: paragraph }, paragraph))) })] }) }, section.heading))) }) }), _jsxs("section", { className: "section-shell pt-0", children: [_jsx(SectionHeading, { eyebrow: "Related", title: "More reading", description: "Keep exploring the content that supports smarter matching and safer conversations." }), _jsx("div", { className: "mt-10", children: _jsx(RelatedArticles, { article: article }) })] })] }));
}
export function FaqPage() {
    const [query, setQuery] = useState("");
    const groups = categorizedFaqs
        .map((group) => ({
        ...group,
        items: group.items.filter((item) => `${item.question} ${item.answer}`.toLowerCase().includes(query.trim().toLowerCase()))
    }))
        .filter((group) => group.items.length > 0);
    return (_jsxs("div", { children: [_jsx("section", { className: "section-shell pb-10 pt-16", children: _jsx(SectionHeading, { eyebrow: "FAQ", title: "Search the questions users ask before they trust a marriage platform", description: "Searchable FAQs across matching, safety, genotype, messaging, and account controls." }) }), _jsx("section", { className: "section-shell pt-0", children: _jsx("div", { className: "surface-card p-6 sm:p-8", children: _jsxs("label", { className: "grid gap-2", children: [_jsx("span", { className: "text-sm font-semibold text-brand-forest", children: "Search the FAQ" }), _jsx("input", { className: "input-shell", value: query, onChange: (event) => setQuery(event.target.value), placeholder: "Search matching, genotype, messaging..." })] }) }) }), _jsx("section", { className: "section-shell pt-0", children: _jsx("div", { className: "grid gap-8", children: groups.map((group, index) => (_jsx(RevealOnScroll, { delay: index * 70, children: _jsxs("div", { className: "surface-card p-7", children: [_jsx("h2", { className: "font-display text-3xl font-semibold text-brand-ink", children: group.category }), _jsx("div", { className: "mt-6 grid gap-4", children: group.items.map((item) => (_jsxs("details", { className: "rounded-[1.5rem] border border-brand-forest/10 bg-brand-forest/5 px-5 py-4", children: [_jsx("summary", { className: "cursor-pointer list-none font-semibold text-brand-ink", children: item.question }), _jsx("p", { className: "mt-4 text-sm leading-7 text-brand-forest/80", children: item.answer })] }, item.question))) })] }) }, group.category))) }) })] }));
}
export function LegalPage({ eyebrow, title, description, sections }) {
    return (_jsxs("div", { children: [_jsx("section", { className: "section-shell pb-10 pt-16", children: _jsx(SectionHeading, { eyebrow: eyebrow, title: title, description: description }) }), _jsx("section", { className: "section-shell pt-0", children: _jsx("div", { className: "mx-auto max-w-4xl grid gap-6", children: sections.map((section) => (_jsxs("article", { className: "surface-card p-8", children: [_jsx("h2", { className: "font-display text-3xl font-semibold text-brand-ink", children: section.heading }), _jsx("div", { className: "mt-5 grid gap-4 text-base leading-8 text-brand-forest/80", children: section.body.map((paragraph) => (_jsx("p", { children: paragraph }, paragraph))) })] }, section.heading))) }) })] }));
}
