import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Dna, ShieldCheck } from "lucide-react";
import { GenotypeChecker } from "@/components/GenotypeChecker";
import { Seo } from "@/components/Seo";
import { SectionHeading } from "@/components/SectionHeading";
import { genotypeCompatibilityTable } from "@/lib/genotype";
export function GenotypePage() {
    return (_jsxs("div", { children: [_jsx(Seo, { title: "Genotype Guide \u2014 AA, AS, SS Compatibility", description: "Understand genotype compatibility in Nigerian marriages. Sacred Match integrates AA, AS, and SS genotype awareness privately into the matchmaking process.", canonical: "https://sacred-match.ng/genotype-guide" }), _jsx("section", { className: "section-shell pb-10 pt-16", children: _jsx(SectionHeading, { eyebrow: "Genotype feature", title: "A medically sensitive feature built into the matchmaking journey", description: "Sacred Match treats genotype compatibility as an informed-decision layer with privacy, education, and counseling-oriented product language." }) }), _jsx("section", { className: "section-shell pt-0", children: _jsx(GenotypeChecker, {}) }), _jsx("section", { className: "section-shell pt-0", children: _jsxs("div", { className: "grid gap-6 lg:grid-cols-[0.9fr_1.1fr]", children: [_jsxs("div", { className: "surface-card p-7", children: [_jsx("div", { className: "flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-emerald/10 text-brand-emerald", children: _jsx(Dna, { size: 22 }) }), _jsx("h2", { className: "mt-6 font-display text-3xl font-semibold text-brand-ink", children: "What the feature needs to do" }), _jsxs("div", { className: "mt-5 grid gap-4 text-sm leading-7 text-brand-forest/80", children: [_jsx("p", { children: "Explain AA, AS, and SS in direct language that does not trivialize sickle-cell risk." }), _jsx("p", { children: "Allow users to control when genotype is shown and to whom it becomes visible." }), _jsx("p", { children: "Trigger counseling prompts for caution and high-risk pairings instead of only color labels." }), _jsx("p", { children: "Support future integrations with verified testing labs and medical education content." })] })] }), _jsxs("div", { className: "surface-card p-7", children: [_jsx("div", { className: "flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-clay/10 text-brand-clay", children: _jsx(ShieldCheck, { size: 22 }) }), _jsx("h2", { className: "mt-6 font-display text-3xl font-semibold text-brand-ink", children: "Public matrix shipped in this foundation" }), _jsx("div", { className: "mt-6 grid gap-3", children: genotypeCompatibilityTable.map((entry) => (_jsxs("div", { className: "flex items-center justify-between rounded-[1.5rem] border border-brand-forest/10 bg-brand-forest/5 px-5 py-4 text-sm", children: [_jsxs("span", { className: "font-semibold text-brand-ink", children: [entry.left, " + ", entry.right] }), _jsx("span", { className: "rounded-full bg-white px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-brand-forest", children: entry.label })] }, `${entry.left}-${entry.right}`))) })] })] }) })] }));
}
